<?php

namespace Tests\Feature\Invoicing;

use App\Domains\Accounting\Models\VatRate;
use App\Domains\Contacts\Models\Contact;
use App\Domains\Invoicing\Actions\DuplicateInvoiceAction;
use App\Domains\Invoicing\Models\Invoice;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Inertia\Testing\AssertableInertia;
use Tests\TestCase;
use Tests\Traits\WithAuthenticatedOrganization;

/** The invoice introduction (text before the line items) through the web form, the API and duplication. */
class InvoiceIntroductionTest extends TestCase
{
    use RefreshDatabase, WithAuthenticatedOrganization;

    private Contact $customer;

    private VatRate $vatRate;

    protected function setUp(): void
    {
        parent::setUp();
        $this->setUpOrganization();
        $this->customer = Contact::factory()->create(['organization_id' => $this->org->id]);
        $this->vatRate = VatRate::factory()->create(['organization_id' => $this->org->id, 'rate' => 8.10]);
    }

    /** @return array<string, mixed> */
    private function payload(array $extra = []): array
    {
        return [
            'customer_id' => $this->customer->id,
            'number' => 'INV-INTRO-001',
            'issue_date' => '2026-05-01',
            'due_date' => '2026-05-31',
            'currency' => 'CHF',
            'lines' => [['description' => 'Service', 'quantity' => 1, 'unit_price' => 100, 'vat_rate_id' => $this->vatRate->id]],
            ...$extra,
        ];
    }

    public function test_the_introduction_is_stored_and_updated_from_the_form(): void
    {
        $this->actAsOrg()->post(route('invoices.store'), $this->payload(['introduction' => 'Mandat de conseil']))->assertSessionHasNoErrors()->assertRedirect();
        $invoice = Invoice::query()->where('organization_id', $this->org->id)->sole(); // the number is generated by the controller
        $this->assertSame('Mandat de conseil', $invoice->introduction);

        $this->actAsOrg()->put(route('invoices.update', $invoice), $this->payload(['introduction' => '']))->assertRedirect();
        $this->assertNull($invoice->fresh()->introduction);

        $this->actAsOrg()->put(route('invoices.update', $invoice), $this->payload(['introduction' => str_repeat('x', 5001)]))
            ->assertSessionHasErrors('introduction');
    }

    public function test_an_invoice_with_a_text_line_can_be_saved_from_the_form(): void
    {
        // The form sends a text line with quantity 0 (it has none); an item still needs a quantity.
        $lines = [
            ['type' => 'text', 'description' => 'Option : suivi mensuel sur demande.', 'quantity' => '0.00', 'unit_price' => '0.00'],
            ['description' => 'Service', 'quantity' => 1, 'unit_price' => 100, 'vat_rate_id' => $this->vatRate->id],
        ];
        $this->actAsOrg()->post(route('invoices.store'), $this->payload(['lines' => $lines]))->assertSessionHasNoErrors()->assertRedirect();
        $invoice = Invoice::query()->where('organization_id', $this->org->id)->sole();
        $this->assertSame(2, $invoice->lines()->count());

        $this->actAsOrg()->put(route('invoices.update', $invoice), $this->payload(['lines' => $lines]))->assertSessionHasNoErrors()->assertRedirect();

        $lines[1]['quantity'] = 0;
        $errors = $this->actAsOrg()->put(route('invoices.update', $invoice), $this->payload(['lines' => $lines]))
            ->assertSessionHasErrors('lines.1.quantity')->baseResponse->getSession()->get('errors');
        $this->assertStringNotContainsString('app.', $errors->first('lines.1.quantity'), 'A translated message');
        $this->assertStringContainsString('0.01', $errors->first('lines.1.quantity'));
    }

    public function test_the_show_page_and_the_duplicate_carry_the_introduction(): void
    {
        $invoice = Invoice::factory()->create(['organization_id' => $this->org->id, 'customer_id' => $this->customer->id, 'introduction' => 'Concerne : projet X']);

        $this->actAsOrg()->get(route('invoices.show', $invoice))
            ->assertInertia(fn (AssertableInertia $page) => $page->where('invoice.introduction', 'Concerne : projet X'));

        $copy = app(DuplicateInvoiceAction::class)->execute($invoice);
        $this->assertSame('Concerne : projet X', $copy->introduction);
    }
}
